name: Auto Clean

on:
  # 自动清理：UTC+8时区每隔2天的凌晨1:15触发
  schedule:
    - cron: '15 17 */2 * *'  

  # 手动触发
  workflow_dispatch:
    inputs:
      NUMBER:
        description: '保留releases数量:'
        default: '6'
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  write-all

jobs:
  auto_clean_and_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: ${{ inputs.NUMBER || '6' }}
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5

     
