name: Auto Sync Fork

on:
  # 自动清理：UTC+8时区每隔2天的凌晨1:15触发
  #schedule:
  #  - cron: '15 17 */2 * *'  

  # 手动触发
  workflow_dispatch:
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  write-all

jobs:
  auto_sync:
    runs-on: ubuntu-latest
    steps:
      

      - name: Checkout Code for VIKINGYFY immortalwrt
        uses: actions/checkout@v4
        with:
          repository: 'YunHair/immortalwrt'
          token: ${{ secrets.PAT_REPO}}
          fetch-depth: 0  # Fetch all history so that we have a full clone

      - name: Sync with Upstream for VIKINGYFY immortalwrt
        run: |     
          git remote add upstream https://github.com/VIKINGYFY/immortalwrt.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main

      - name: Checkout Code for LiBwrt
        uses: actions/checkout@v4
        with:
          repository: 'YunHair/LiBwrt'
          token: ${{ secrets.PAT_REPO }}
          fetch-depth: 0  # Fetch all history so that we have a full clone

      - name: Sync with Upstream for LiBwrt
        run: |
          git remote add upstream https://github.com/LiBwrt-op/openwrt-6.x.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main
